[package]
name = "functionsExamples"
version = "0.1.0"
edition = "2021"

#Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3


[dependencies] 
bevy = "0.11"
rand = "0.8"